.distribution: &distribution
    versions: [ supported ]
    repository: &repository
        name: pdidev
        description: "PDI dev packages"
    gpg:
        file: "key.gpg"
distribs:
    debian:
        <<: *distribution
        versions: [ supported, testing, sid ]
        repository:
            <<: *repository
            path: "debian"
            url: "https://repo.pdi.dev/debian/"
    ubuntu:
        <<: *distribution
        repository:
            <<: *repository
            path: "ubuntu"
            url: "https://repo.pdi.dev/ubuntu/"
    fedora:
        <<: *distribution
        repository:
            <<: *repository
            path: "fedora"
            url: "https://repo.pdi.dev/fedora/"
packages:
    paraconf:
        orig: "https://github.com/pdidev/paraconf/archive/{upstream_version}.tar.gz"
    pdi:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
    pdidev-archive-keyring:
        disable: { fedora: all }
    pdiplugin-decl-hdf5:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
    pdiplugin-decl-netcdf:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
    pdiplugin-mpi:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
    pdiplugin-pycall:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
    pdiplugin-serialize:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
    pdiplugin-set-value:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
    pdiplugin-trace:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
    pdiplugin-user-code:
        orig: "https://github.com/pdidev/pdi/archive/refs/heads/{upstream_version}.tar.gz"
