#!/bin/bash
set -e

if [ $# -lt 1 -o $# -gt 1 ]
then
    echo "Usage: $0 <directory>" >&2
    exit 1
fi

RUNDIR="$PWD"

PKGNAME="$(basename "$1")"
cd "${PKGNAME}"
PKGDIR="$PWD"
cd "${RUNDIR}"

ROOTDIR="$(dirname "$0")"
cd "${ROOTDIR}"
ROOTDIR="$PWD"
cd "${RUNDIR}"

cd "$(mktemp -d --tmpdir LOCAL.XXXXXXXXXXXX.tmdir || exit 1)"
WKDIR="${PWD}"
trap "cd '${RUNDIR}'; rm -rf '${WKDIR}'" EXIT

cd "${WKDIR}"
"${ROOTDIR}/obs_data_gen" "${PKGDIR}"
tar -xf "${PKGNAME}-obs_repodata.tar"
tar -xf "${PKGNAME}-obs_rundata.tar"
rm *.tar

cd "${WKDIR}"
apt-get update -qq
mk-build-deps -r -t "apt-get -y --no-install-recommends -qq" -i *.dsc
dpkg-source -x "${PKGNAME}_"*".dsc"
cd "$(find . -type d -name "${PKGNAME}-*")"
dpkg-buildpackage --no-sign

cd "${WKDIR}"
rm -rf "$(find . -maxdepth 1 -type d -name "${PKGNAME}-*")"
chown $(stat -c '%u:%g' "${RUNDIR}") *.deb *.dsc "${PKGNAME}_"*".debian.tar."* "${PKGNAME}_"*".orig.tar."*
mv *.deb *.dsc "${PKGNAME}_"*".debian.tar."* "${PKGNAME}_"*".orig.tar."* "${RUNDIR}"/
