#!/bin/bash
set -e

if [ $# -ne 1 ]
then
    echo "Usage: $0 <directory>" >&2
    exit 1
fi

RUNDIR="${PWD}"

cd "$1"
SRCDIR="${PWD}"

PKGNAME="$(dpkg-parsechangelog -n 1 -S Source)"
PKGVERS="$(dpkg-parsechangelog -n 1 -S Version)"
SRCVERS="$(echo "${PKGVERS}" | sed -e 's/.*://' -e 's/-.*//' )"
SRCURL="$(eval echo "$(cat src_url)")"
SRCEXT="$(basename "${SRCURL}"| sed 's/.*\.//')"

cd "$(mktemp -d --tmpdir BUILDER.XXXXXXXXXXXX.tmdir || exit 1)"
DSTDIR="${PWD}"
trap "cd '${RUNDIR}'; rm -rf '${DSTDIR}'" EXIT

curl -L -s "${SRCURL}" -o "${PKGNAME}_${SRCVERS}.orig.tar.${SRCEXT}"

mkdir -p "${PKGNAME}-${PKGVERS}"
cd "${PKGNAME}-${PKGVERS}"

tar --strip-components=1 -xf "../${PKGNAME}_${SRCVERS}.orig.tar.${SRCEXT}"
cp -r "${SRCDIR}/debian" .

cd ..
dpkg-source -b "${PKGNAME}-${PKGVERS}"
rm -r "${PKGNAME}-${PKGVERS}"

if [ -e "${SRCDIR}"/*.spec ]
then
    cp "${SRCDIR}"/*.spec .
fi
if [ -e "${SRCDIR}"/*.changes ]
then
    cp "${SRCDIR}"/*.changes .
fi

tar -cf "${PKGNAME}-obs_repodata.tar" *
tar -cf "${PKGNAME}-obs_rundata.tar" -T /dev/null # kept for compatibility
mv "${PKGNAME}-obs_"*"data.tar" "${RUNDIR}/"
