#!/bin/bash

if [ $# -ne 1 ]
then
    echo "Usage: $0 <directory>" >&2
    exit 1
fi

cd "$1"

PKGNAME="$(awk '/Source:/ { print $2 }' "debian/control")"
PKGVERS="$(awk '/urgency\s*=/ { sub("\\(", "", $2); sub("\\)", "", $2); print $2; exit }' "debian/changelog")"
SRCVERS="$(echo "${PKGVERS}" | sed 's/-.*//')"
SRCURL="$(eval echo "$(cat src_url)")"

cat <<EOF > "${PKGNAME}.dsc"
Format: 3.0 (quilt)
Source: ${PKGNAME}
Binary: $(awk '/Package:/ { ORS=","; print $2 }' "debian/control" | sed 's/,$//')
Architecture: any
Version: ${PKGVERS}
Maintainer: Julien Bigot <julien.bigot@cea.fr>
Standards-Version: 4.5.0
$(grep 'Build-Depends:' "debian/control")
Files:
 aaa 000 ${SRCURL}
 aaa 000 https://github.com/${GITHUB_REPOSITORY}/releases/download/${RELEASE_NAME}/${PKGNAME}.debian.tar.xz
EOF

cat <<EOF > "${PKGNAME}.spec"
Source0: ${SRCURL}
Source1: https://github.com/${GITHUB_REPOSITORY}/releases/download/${RELEASE_NAME}/${PKGNAME}.debian.tar.xz
EOF

rm -f "${PKGNAME}.debian.tar.xz" &> /dev/null
tar -cJf "${PKGNAME}.debian.tar.xz" debian/
