#!/bin/bash
set -x

if [ $# -lt 1 -o $# -gt 2 ]
then
    echo "Usage: $0 <directory> [<tmpdir>]" >&2
    exit 1
fi

RUNDIR="${PWD}"

cd "$1"
SRCDIR="${PWD}"

PKGNAME="$(awk '/Source:/ { print $2 }' "debian/control")"
PKGVERS="$(awk '/urgency\s*=/ { sub("\\(", "", $2); sub("\\)", "", $2); print $2; exit }' "debian/changelog")"
SRCVERS="$(echo "${PKGVERS}" | sed -e 's/.*://' -e 's/-.*//' )"
SRCURL="$(eval echo "$(cat src_url)")"
SRCEXT="$(basename "${SRCURL}"| sed 's/.*\.//')"

if [ $# -eq 2 ]
then
    mkdir -p "$2"
    cd "$2"
    DSTDIR="${PWD}"
else
    cd "$(mktemp -d --tmpdir BUILDER.XXXXXXXXXXXX.tmdir || exit 1)"
    DSTDIR="${PWD}"
    trap "cd '${RUNDIR}'; rm -rf '${DSTDIR}'" EXIT
fi

curl -s "${SRCURL}" -o "${PKGNAME}_${SRCVERS}.orig.tar.${SRCEXT}"

mkdir -p "${PKGNAME}-${PKGVERS}"
cd "${PKGNAME}-${PKGVERS}"

tar --strip-components=1 -xf "../${PKGNAME}_${SRCVERS}.orig.tar.${SRCEXT}"
cp -r "${SRCDIR}/debian" .

cd ..
dpkg-source -b "${PKGNAME}-${PKGVERS}"
rm -r "${PKGNAME}-${PKGVERS}"

tar -cf "${PKGNAME}-obs_rundata.tar" "${PKGNAME}_${SRCVERS}.orig.tar.${SRCEXT}" "${PKGNAME}_${PKGVERS}.debian.tar.xz"
mv "${PKGNAME}-obs_rundata.tar" "${RUNDIR}/"
rm "${PKGNAME}_${SRCVERS}.orig.tar.${SRCEXT}" "${PKGNAME}_${PKGVERS}.debian.tar.xz"

if [ -e "${SRCDIR}"/*.spec ]
then
    cp "${SRCDIR}"/*.spec .
fi
if [ -e "${SRCDIR}"/*.changes ]
then
    cp "${SRCDIR}"/*.changes .
fi

tar -cf "${PKGNAME}-obs_repodata.tar" *
mv "${PKGNAME}-obs_repodata.tar" "${RUNDIR}/"
