#!/bin/bash
set -e

if [ $# -lt 1 -o $# -gt 1 ]
then
    echo "Usage: $0 <token>" >&2
    exit 1
fi

OUTPUT="$(curl -s 'https://build.opensuse.org/trigger/runservice' -X POST -H "Authorization: Token $1" )"
if echo "${OUTPUT}" | grep -q -s -e 'status\s*code="ok"'
then
	echo "${OUTPUT}"
fi
