#!
set -e

case #FLAVOR# in
#ARCH_DEFAULT_MPI_IMPL#)
	PRIORITY=30
	;;
*)
	PRIORITY=10
	;;
esac

case "$1" in
configure)
	update-alternatives \
		--install \
		/usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)/libfti.so \
		libfti.so-$(dpkg-architecture -qDEB_HOST_MULTIARCH) \
		/usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)/fti/#FLAVOR#/libfti.so \
		${PRIORITY}
;;
*)
	# nothing to do
;;
esac

#DEBHELPER#
