name: Aggregate step
description: 'Aggregate packages from all distributions'
inputs:
  GITHUB_TOKEN:
    required: true
    description: "GITHUB_TOKEN"
runs:
  using: "composite"
  steps:
    - name: Aggregate sources
      id: ident
      shell: bash
      run: |
        for DISTRIB in debian fedora ubuntu pdi-main.debian pdi-main.fedora pdi-main.ubuntu
        do
          CID="$(docker create ghcr.io/pdidev/pkgs/lastbuild:debian /bin/bash)"
          docker cp "${CID}:run_id" "${DISTRIB}.run_id"
          echo "${DISTRIB}_run_id=$(cat ${DISTRIB}.run_id)\n" >> $GITHUB_OUTPUT
        done
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: debian
        github-token: ${{ inputs.GITHUB_TOKEN }}
        run-id: ${{steps.ident.outputs.debian_run_id}}
        path: _site/debian
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: fedora
        github-token: ${{ inputs.GITHUB_TOKEN }}
        run-id: ${{steps.ident.outputs.fedora_run_id}}
        path: _site/fedora
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: ubuntu
        github-token: ${{ inputs.GITHUB_TOKEN }}
        run-id: ${{steps.ident.outputs.ubuntu_run_id}}
        path: _site/ubuntu
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: pdi-main.debian
        github-token: ${{ inputs.GITHUB_TOKEN }}
        run-id: ${{steps.ident.outputs.debian_run_id}}
        path: _site/pdi-main.debian
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: pdi-main.fedora
        github-token: ${{ inputs.GITHUB_TOKEN }}
        run-id: ${{steps.ident.outputs.fedora_run_id}}
        path: _site/pdi-main.fedora
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: pdi-main.ubuntu
        github-token: ${{ inputs.GITHUB_TOKEN }}
        run-id: ${{steps.ident.outputs.ubuntu_run_id}}
        path: _site/pdi-main.ubuntu
    - name: Link to pdi-master
      shell: bash
      run: |
        set -x
        ls -R
        cd _site
        for DISTRIB in debian fedora ubuntu
        do 
          if [ -d "pdi-main.${DISTRIB}" ]
          then ln -s "pdi-master.${DISTRIB}" "pdi-main.${DISTRIB}"
          fi
        done
        ls -R
    - name: Upload page artifact
      uses: actions/upload-pages-artifact@v3
