name: OBS

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        path: source
    - name: Checkout generated
      uses: actions/checkout@v2
      with:
        ref: generated
        path: generated
        fetch-depth: 0
    - name: Deploy
      run: |
        set -x
        cd source
        find . -maxdepth 1 -type d '!' -name '.*' -exec ./obs_data_gen '{}' ';'
        rm -rf ../generated/* || true
        mv *-obs_*data.tar ../generated
        cd ../generated
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@noreply.example.com"
        git add -A .
        git commit -a --amend
        git push -f
