name: OBS

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        path: source
    - name: Checkout generated
      uses: actions/checkout@v2
      with:
        ref: generated
        path: generated
        fetch-depth: 0
    - run: cd source
    - run: "find . -maxdepth 1 -type d '!' -name '.*' -exec ./obs_data_gen '{}' ';'"
    - run: |
        rm ../generated/*
        mv *-obs_*data.tar ../generated
        cd ../generated
        git add -A .
        git commit -a --amend
        git push -f
