name: Test PDI issue fix branch
on:
  push:
    branches: [ 'wait4upstream/*' ]
  #TODO: enable scheduled run for the correct branch,
  #      this would run on the default branch instead
  #schedule:
    #- cron:  '47 3 * * 6' # weekly build on Saturday, 3:47AM
jobs:
  build_and_publish:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distrib: [ debian, fedora, ubuntu ]
    steps:
      - name: Checkout packages
        uses: actions/checkout@v2
        with:
          ref: "${{ github.head_ref }}"
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Checkout builder script
        uses: actions/checkout@v2
        with:
          repository: jbigot/pkg_builder
          path: pkg_builder
      - name: Install deps
        run: |
          sudo curl -o /etc/apt/trusted.gpg.d/deb.myguard.nl.gpg https://deb.myguard.nl/pool/deb.myguard.nl.gpg
          . /etc/os-release
          echo "deb [arch=amd64] http://deb.myguard.nl $VERSION_CODENAME main" | sudo tee /etc/apt/sources.list.d/deb.myguard.nl.list
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install devscripts equivs aptly
          pip3.8 install -r pkg_builder/requirements.txt
      - name: Build packages
        env:
          KEY_PASSPHRASE: ${{ secrets.KEY_PASSPHRASE }}
          DISTRIB: ${{ matrix.distrib }}
        run: |
          python3.8 pkg_builder/pkgbuild -D ${DISTRIB} -j 3 -p "${KEY_PASSPHRASE}"
